name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      # Step 2: Install Git LFS
      - name: Install Git LFS
        run: git lfs install

      # Step 3: Track .nc files with LFS
      - name: Track .nc files with LFS
        run: git lfs track "*.nc"

      # Step 4: Pull LFS files (if needed)
      - name: Pull LFS files
        run: git lfs pull

      # Step 5: Configure Git user
      - name: Configure Git user
        run: |
          git config --global user.email "your_email@example.com"
          git config --global user.name "Your Name"

      # Step 6: Check for changes (logging step)
      - name: Check for changes
        run: |
          git status
          git lfs ls-files

      # Step 7: Push changes to Hugging Face hub
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git add -f .
          
          # Check if there are any changes to commit
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "Update from GitHub Actions"
            git push https://alexdum:$HF_TOKEN@huggingface.co/spaces/alexdum/roclihom main
          fi
