name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository with full history and LFS support
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history to allow for force pushing
          lfs: true       # Enable Git LFS

      # Step 2: Install Latest Git LFS
      - name: Install Latest Git LFS
        run: |
          # Remove any existing Git LFS installation
          sudo apt-get remove git-lfs || true
          
          # Add the Git LFS repository
          curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
          
          # Install Git LFS
          sudo apt-get install git-lfs
          
          # Initialize Git LFS
          git lfs install

      # Step 3: Configure Git User
      - name: Configure Git User
        run: |
          git config --global user.email "alexandru.dumitrescu@gmail.com"
          git config --global user.name "alexdum"

      # Step 4: Track All .nc Files with Git LFS
      - name: Track .nc Files with Git LFS
        run: |
          git lfs track "*.nc"
          git add .gitattributes
          git commit -m "Configure Git LFS for all .nc files" || echo "No changes to .gitattributes"

      # Step 5: Migrate Existing .nc Files to Git LFS
      - name: Migrate Existing .nc Files to Git LFS
        run: |
          git lfs migrate import --include="*.nc" --everything

      # Step 6: Add and Commit Any LFS-tracked Files
      - name: Add and Commit LFS-tracked Files
        run: |
          git add .
          git commit -m "Move .nc files to Git LFS" || echo "No changes to commit"

      # Step 7: Verify LFS Tracking
      - name: Verify LFS Tracking
        run: git lfs ls-files

      # Step 8: Add Hugging Face Remote
      - name: Add Hugging Face Remote
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://alexdum:${HF_TOKEN}@huggingface.co/spaces/alexdum/roclihom

      # Step 9: Force Push to Hugging Face Hub
      - name: Force Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push hf main --force
