name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository with full history and LFS support
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history
          lfs: true       # Enable Git LFS

      # Step 2: Install Latest Git LFS
      - name: Install Latest Git LFS
        run: |
          # Remove any existing Git LFS installation
          sudo apt-get remove git-lfs || true
          
          # Add the Git LFS repository
          curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
          
          # Install Git LFS
          sudo apt-get install git-lfs
          
          # Initialize Git LFS
          git lfs install

      # Step 3: Configure Git user
      - name: Configure Git user
        run: |
          git config --global user.email "your_email@example.com"
          git config --global user.name "Your Name"

      # Step 4: Track .nc files with Git LFS
      - name: Track .nc files with Git LFS
        run: |
          git lfs track "*.nc"
          git add .gitattributes
          git commit -m "Configure Git LFS for .nc files" || echo "No changes to .gitattributes"

      # Step 5: Migrate existing large files to Git LFS (if necessary)
      - name: Migrate existing large files to Git LFS
        run: |
          git lfs migrate import --include="www/data/ncs/tcdc.convcld.1981.nc" --everything

      # Step 6: Add large files to Git
      - name: Add large files to Git
        run: |
          git add www/data/ncs/tcdc.convcld.1981.nc
          git commit -m "Add large .nc file with Git LFS" || echo "No changes to large files"

      # Step 7: Verify LFS tracking
      - name: Verify LFS tracking
        run: git lfs ls-files

      # Step 8: Fetch and Merge Remote Changes
      - name: Fetch and Merge Remote Changes
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://alexdum:${HF_TOKEN}@huggingface.co/spaces/alexdum/roclihom
          git fetch hf
          git merge hf/main || git rebase hf/main

      # Step 9: Push commits to Hugging Face hub
      - name: Push commits to Hugging Face hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push hf main

      # Step 10: Push LFS objects to Hugging Face hub
      - name: Push LFS objects to Hugging Face hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git lfs push hf main
