- name: Push to hub
  env:
    HF_TOKEN: ${{ secrets.HF_TOKEN }}
  run: |
    git add -f .
    
    # Check if there are any changes to commit
    if git diff-index --quiet HEAD --; then
      echo "No changes to commit"
    else
      git commit -m "Update from GitHub Actions"
      git push https://alexdum:$HF_TOKEN@huggingface.co/spaces/alexdum/roclihom main
    fi
